// mocks/app-renderer-solid/routes/_renderer.tsx
/** @jsxImportSource solid-js */
import { createMiddleware } from 'hono/factory'
import { HydrationScript, renderToString } from 'solid-js/web'

export default createMiddleware(async (c, next) => {
  c.setRenderer(((content: unknown) =>
    c.html(
      '<!DOCTYPE html>' +
        renderToString(() => (
          <html>
            <head>
              <HydrationScript />
            </head>
            <body>
              {content as never}
              <script type='module' src='/client.ts' />
            </body>
          </html>
        ))
    )) as never)
  await next()
})

// mocks/app-renderer-preact/routes/_renderer.tsx
/** @jsxImportSource preact */
import { createMiddleware } from 'hono/factory'
import renderToString from 'preact-render-to-string'

export default createMiddleware(async (c, next) => {
  c.setRenderer(((content: unknown) =>
    c.html(
      '<!DOCTYPE html>' +
        renderToString(
          <html>
            <body>
              {content}
              <script type='module' src='/client.ts' />
            </body>
          </html>
        )
    )) as never)
  await next()
})
