// mocks/app-renderer-preact/islands/IdProbe.tsx
/** @jsxImportSource preact */
import { useId } from 'preact/hooks'

export default function IdProbe({ name }: { name: string }) {
  const id = useId()

  return (
    <button
      data-probe={name}
      data-render-id={id}
      onClick={(event) => {
        event.currentTarget.dataset.clientId = id
      }}
    >
      {name}
    </button>
  )
}

// mocks/app-renderer-vue/islands/IdProbe.tsx
/** @jsxImportSource vue */
import { useId } from 'vue'

export default function IdProbe({ name }: { name: string }) {
  const id = useId()

  return (
    <button
      data-probe={name}
      data-render-id={id}
      onClick={(event) => {
        const button = event.currentTarget as HTMLButtonElement
        button.dataset.clientId = id
      }}
    >
      {name}
    </button>
  )
}
