// mocks/app-renderer-react/islands/IdProbe.tsx
/** @jsxImportSource react */
import { useId } from 'react'

export default function IdProbe({ name }: { name: string }) {
  const id = useId()

  return (
    <button
      data-probe={name}
      data-render-id={id}
      onClick={(event) => {
        event.currentTarget.dataset.clientId = id
      }}
    >
      {name}
    </button>
  )
}

// mocks/app-renderer-solid/islands/IdProbe.tsx
/** @jsxImportSource solid-js */
import { createUniqueId } from 'solid-js'

export default function IdProbe(props: { name: string }) {
  const id = createUniqueId()

  return (
    <button
      data-probe={props.name}
      data-render-id={id}
      onClick={(event) => {
        event.currentTarget.dataset.clientId = id
      }}
    >
      {props.name}
    </button>
  )
}
